name: cloud_firestore_custom
description: A custom Firestore plugin extracted from FlutterFire for testing and CocoaPods compatibility
version: 0.0.1
homepage: https://github.com/damianotosi1973/cloud_firestore_custom
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0
  collection: ^1.18.0
  firebase_core: ^2.25.4
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.15.0
  cloud_firestore_platform_interface: ^6.6.9
  cloud_firestore_web: ^4.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets: []
